### ISSUE TITLE
Create a Website to Chat Within Online

### ISSUE THREAD

**Issue by una** [opensourcedesign/slick#1]
A web link we can go to and chat :)

Using http://shout-irc.com/

**Comment by jancborchardt** [comment]
@henne you mentioned you might be able to help here? :)

It would be cool if we can get Shout configured to make new people automatically join freenode with #opensourcedesign. And maybe even some other open source design channels (#drupal-usability, #wikimedia-design, #owncloud-design etc)

**Comment by una** [comment]
Sorry I should have mentioned in the title of the issue -- a Web Chat

**Comment by flexbox** [comment]
@una 
The idea is great but i think shout add some complexity.

Here is my point of view :
- People here have all a GitHub account
- They want to talk simply without create another Login / password

Gitter is perfect for that https://gitter.im

What do you think ?

**Comment by raucao** [comment]
We're working on an open source Web app to fix IRC for humans, but it's too young to use yet. You can follow our progress here: https://twitter.com/join67p

Until then, you can already use a simple IRC widget with the base tech we're using. There's a node.js open-source commodity server called [Sockethub](https://github.com/sockethub/sockethub) doing the connections, and talking to client-side apps/websites via JSON Activity Streams. We have a chat widget for embedding IRC in websites called [Guppy](https://github.com/silverbucket/guppy-irc). It's pretty easy to add and style.

Let me know if you're interested in this, and we can help you set it up. /cc @silverbucket

**Comment by simonv3** [comment]
@flexbox I'm hesitant to locking ourselves into Github, and also expecting all designers to have an account on Github, I'd prefer something open like IRC.

@skddc That sounds pretty exciting, I'd love to find out a bit more.

**Comment by jancborchardt** [comment]
@flexbox @simonv3 yeah, this idea is specifically about lowering barriers. We can’t expect all designers to have a Github account. Shout, with some modifications, makes for an easy way for anyone to join the #opensourcedesign chat via web.

**Comment by una** [comment]
Would love to get insight from designers who don't have a Github account, but I do think it is reasonable to ask designers to create a free Github account to join the community.

Seems like a pretty small barrier that could solve more communication barriers in the future. 

Getting designers onto Github is actually a solution in my opinion, even if they aren't pushing code.

**Comment by jdittrich** [comment]
I agree with @jancborchardt. Creating an account is always a small barrier – in particular if people (here: designers)  are not sure about the value of the service (github) for them.

@jancborchardt did you ever try/configure shout on you own node instance?

**Comment by una** [comment]
@jdittrich @jancborchardt the service is free, however. I think ultimately, designers will need to create an account to have a say. It is similar to a message board in that aspect.

**Comment by simonv3** [comment]
@una @jdittrich @jancborchardt my concern also stems from the equating github (a not opensource but for-profit company) with opensource software angle. It's not a huge issue, I love the service they provide, and I think they do it really well, and the majority of OSS is hosted on it, but I feel like saying "you have to have a github account to participate in OSS" does send a message along those lines, whereas that's not the case at all.

On the other hand, for the sake of a minimum meaningful product, having a chat room now that's powered by gitter might be a good temporary solution while Shout is figured out.

On that note, what is actually blocking on Shout? *_Edit: *_ if it's installing on a server, I'm happy to try to get something going on mine, but that probably wouldn't fall nicely underneath the current website, though we could probably propagate shout.opendesign.com to that.

**Comment by qwazix** [comment]
I'd rather see a "stackoverflowy" style website, so that communications stay searchable and relevant for the rest of the community. Askbot is a free such solution, or we could just try creating a stack exchange site.

Just an idea.

M.

**Comment by raucao** [comment]
I think this is about text/live chat, not link sharing and commenting.

**Comment by pdurbin** [comment]
Today @bnvk [indicated](https://botbot.me/freenode/opensourcedesign/2015-03-15/?msg=34200047&page=1) that http://chat.opensourcedesign.net may someday be an IRC bridge to a http://matrix.org client but in the meantime I [suggested](https://botbot.me/freenode/opensourcedesign/2015-03-15/?msg=34201851&page=1) pointing http://chat.opensourcedesign.net to https://kiwiirc.com/client/irc.freenode.net/opensourcedesign

I find that kiwiirc client to be a better user experience than https://webchat.freenode.net/?channels=opensourcedesign , which is where http://chat.opensourcedesign.net points right now.

It would be an easy change to make for now. Longer term I'm interested in seeing if the Matrix idea works out.

**Comment by una** [comment]
Okay, after testing out, they both have similar functionality -- so its not a huge deal, but I do like the kiwiirc interface better. So, I agree with @pdurbin about pointing http://chat.opensourcedesign.net to https://kiwiirc.com/client/irc.freenode.net/opensourcedesign :)

**Comment by bnvk** [comment]
@pdurbin @una @jancborchardt @skddc @simonv3 just a lil update where I'm at with this ;)

I've been working quite a bit on exploring options towards this goal and contributing to various projects like the [matrix client](https://github.com/matrix-org/matrix-angular-sdk) and [Shout IRC](http://shout-irc.com). The former is a bit too rough in terms of amount of dev needed + user adoption to justify building on top of it just yet. The later is very _close_ to being good enough and with tad bit more hacking will be.

I hope to work & improve upon Shout to expand the [robustness of their theme-ing feature](https://github.com/erming/shout/issues/387) as then what is useful for our little community will be useful to other communities while being based on open + free IRC instead of using Slack.

**Comment by bnvk** [comment]
This has finally been setup at [chat.opensourcedesign.net](https://chat.opensourcedesign.net) so I'm closing this issue and will track other more design improvements to Slick in separate issues!

**Comment by qwazix** [comment]
How do we sign up for that?

**Comment by elioqoshi** [comment]
@qwazix there you go:
https://github.com/opensourcedesign/organization/issues/70

**Comment by qwazix** [comment]
Ah okay, I didn't realize it's a web irc client. I'll keep using IRC 
directly then. Thanks.
