### ISSUE TITLE
There is no Bower.json file on the shout theme-support branch

### ISSUE THREAD

**Issue by simonv3** [opensourcedesign/slick#11]
So the instruction: 

Install Bower dependencies `bower install`

Doesn't work. If it's okay to just remove I'll glad do a PR with that. But I was wondering if it implied something else that was broken?

**Comment by bnvk** [comment]
That was my goof of updating docs before code... it's there now ;)

**Comment by simonv3** [comment]
:+1:

**Comment by jancborchardt** [comment]
Still getting the error. I don’t see any bower.json in https://github.com/erming/shout/tree/theme-support
