### ISSUE TITLE
Screenshots in Readme

### ISSUE THREAD

**Issue by luzpaz** [opensourcedesign/slick#17]
Can you please add Screenshots of how the theme looks like ? Thanks

**Comment by urbels** [comment]
+1

**Comment by simonv3** [comment]
That's a great idea. Be happy to accept any PRs on this if you've been playing around with Slick.

**Comment by Spodess** [comment]
+1

**Comment by nhooyr** [comment]
Duplicate of #6

**Comment by jancborchardt** [comment]
Closing as duplicate of https://github.com/opensourcedesign/slick/issues/6
