### ISSUE TITLE
Can't enable slick theme

### ISSUE THREAD

**Issue by MorrisJobke** [opensourcedesign/slick#8]
With the standard theme it works just fine. Once I switch the theme to `slick` and reload the page I got the following message:

```
undefined:13
((__t = ( channelsActionable )) == null ? '' : __t) +
          ^
ReferenceError: channelsActionable is not defined
    at eval (eval at template (/home/mjob/Projekte/shout/node_modules/lodash/dist/lodash.js:6306:22), <anonymous>:13:11)
    at Function.template (/home/mjob/Projekte/shout/node_modules/lodash/dist/lodash.js:6312:16)
    at /home/mjob/Projekte/shout/src/server.js:82:13
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
```

I followed the install steps from the readme

**Comment by erming** [comment]
Changing `channelsActionable` to `theme.channels` should solve this problem.

**Comment by bnvk** [comment]
@MorrisJobke sorry about that. This is still early stages, I just got the theme working yesterday and and had a bunch cruft while familiarizing myself with the codebase. The design is not to different yet and I've still got a long to flesh out! Thanks for being eager and testing :)
