### ISSUE TITLE
Can't see anything on localhost:8000 with current setup instructions.

### ISSUE THREAD

**Issue by lewiscowper** [opensourcedesign/slick#9]
I don't know whether I'm missing anything in my config file or what, but I don't seem to be able to get any output from shout before I've even added slick.

Previously I was running into the same issue as #8, now with the new README I don't get as far as a successful run of `node index.js`, even though the config spins up fine.

**Comment by gniezen** [comment]
I saw the same thing while installing Shout's `theme-support` branch last night. I'm assuming the default theme in that branch is broken at the moment. Don't give up hope! :wink: If you continue to add slick as a theme then it does work!

**Comment by simonv3** [comment]
:+1: I can confirm that what @gniezen says works. We should probably update the instructions to state these things.

**Comment by jancborchardt** [comment]
Here’s an update of the instructions, please review: https://github.com/opensourcedesign/slick/pull/15
